//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFCaptureD3D.rc
//
#define ID_FINESHUT_EN                  3
#define IDR_MENU_5MPBW                  101
#define IDD_CHOOSE_DEVICE               102
#define IDD_CAM_CONTROL                 105
#define ID_FINDSHUTTER_EN               105
#define IDD_DAY_NIGHT_SETTINGS          106
#define IDD_VIDEO_QUALITY_CONTROL       107
#define IDD_2D_NOISE_REDUCTION          108
#define IDD_3D_NOISE_REDUCTION          109
#define IDI_ICON1                       110
#define IDI_FX3_CAM                     110
#define IDD_ABOUT                       112
#define IDD_I2C_CONTROL                 114
#define IDD_ZOOM_CONTROL                115
#define IDD_IRIS_CONTROL                116
#define IDD_IMG_CAPTURE                 117
#define IDD_CAM_PARAM_RECOVERY          118
#define IDD_LOGIN                       119
#define IDD_ROI_CONTROL                 120
#define IDD_STILLRES                    122
#define IDD_ENHANCE_CONTROL             123
#define IDR_MENU_5MPCL                  124
#define IDR_MENU_2MPCL                  126
#define IDR_MENUMISU                    127
#define IDD_CAM_CONTROL2MPCL            128
#define IDD_WBL_COLORSUPP               129
#define IDC_LIST1                       1001
#define IDC_DEVICE_LIST                 1001
#define IDC_COMBO1                      1002
#define IDC_COMBO_DAY_NIGHT_MODE        1002
#define IDC_COMBO_WHTBLCMODE            1002
#define IDC_COMBO_3D_NOISE_REDU_MODE    1002
#define IDC_COMBO_GAMMA_MODE            1002
#define IDC_COMBO_DIG_ZOOM              1002
#define IDC_COMBO_LENSE                 1002
#define IDC_COMBO_AE_PRIORITY           1002
#define IDC_COMBO_WHTBLCMODE2           1003
#define IDC_COMBO_BACK_LIGHT            1003
#define IDC_COMBO_OPT_ZOOM              1003
#define IDC_COMBO_CAM_MODE              1004
#define IDC_COMBO_BACK_LIGHT2           1005
#define IDC_COMBO_BLC_WGHT_FACT         1005
#define IDC_COMBO_SHUT_CONTL            1009
#define IDC_COMBO_EDGEENHN_CONTL        1009
#define IDC_STR_SHUT_CONTL              1010
#define IDC_STR_EDGEENHN_CONTL          1010
#define IDC_STR_SEN_UP_MODE             1011
#define IDC_COMBO_SEN_UP_MODE           1012
#define IDC_STR_AE_REF_LVL              1013
#define IDC_STR_GAIN_START_LVL          1013
#define IDC_SLD_AE_REF_LVL              1014
#define IDC_SLD_GAIN_START_LVL          1014
#define IDC_EDIT_AE_REF_LVL             1015
#define IDC_EDIT_GAIN_START_LVL         1015
#define IDC_STR_DAY_NIGHT_SW_DELAY      1016
#define IDC_STR_EXPOSURE_MODE           1016
#define IDC_SLD_DAY_NIGHT_SW_DELAY      1017
#define IDC_COMBO_EXPOSURE_MODE         1017
#define IDC_EDIT_DAY_NIGHT_SW_DELAY     1018
#define IDC_STR_AGC_LVL                 1018
#define IDC_STR_GAIN_END_LVL            1018
#define IDC_STR_DAY_TO_NIGHT_ST_LVL     1019
#define IDC_SLD_AGC_LVL                 1019
#define IDC_SLD_GAIN_END_LVL            1019
#define IDC_SLIDER_DAY_TO_NIGHT_ST_LVL  1020
#define IDC_EDIT_AGC_LVL                1020
#define IDC_EDIT_GAIN_END_LVL           1020
#define IDC_EDIT_DAY_TO_NIGHT_ST_LVL    1021
#define IDC_STR_MIRROR_MODE             1021
#define IDC_STR_AE_HYSTER               1021
#define IDC_STR_NIGHT_TO_DAY_ST_LVL     1022
#define IDC_COMBO_MIRROR_MODE           1022
#define IDC_SLD_AE_HYSTER               1022
#define IDC_SLIDER_NIGHT_TO_DAY_ST_LVL  1023
#define IDC_STR_MAIN_FEQ                1023
#define IDC_EDIT_AE_HYSTER              1023
#define IDC_EDIT_NIGHT_TO_DAY_ST_LVL    1024
#define IDC_COMBO_MAIN_FEQ              1024
#define IDC_STR_AE_CTRLSPEED            1024
#define IDC_SLIDER1                     1025
#define IDC_SLD_BRIGHTNESS              1025
#define IDC_SLD_3D_NOISE_REDU_VAL       1025
#define IDC_SLD_2D_NOISE_REDU_VAL       1025
#define IDC_SLD_MANUAL_IRIS             1025
#define IDC_SLD_DIG_ZOOM_POS            1025
#define IDC_SLD_HPos                    1025
#define IDC_EDIT_BRIGHTNESS             1026
#define IDC_SLD_AUTO_IRIS               1026
#define IDC_STR_EXP_TIME_ABS            1026
#define IDC_EDIT_HPos                   1026
#define IDC_SLD_2D_NR_GAINSTR_VAL       1026
#define IDC_SLD_CONTRAST                1027
#define IDC_SLD_EXP_TIME_ABS            1027
#define IDC_SLD_HSize                   1027
#define IDC_SLD_2D_NR_GAINEND_VAL       1027
#define IDC_EDIT_CONTRAST               1028
#define IDC_EDIT_EXP_TIME_ABS           1028
#define IDC_EDIT_VPos                   1028
#define IDC_SLD_HIGHTLOW_COLSUP_GAIN    1028
#define IDC_SLD_HUE                     1029
#define IDC_EDIT_HSize                  1029
#define IDC_SLD_EDGE_COLSUP_GAIN        1029
#define IDC_EDIT_HUE                    1030
#define IDC_EDIT_VSize                  1030
#define IDC_SLD_SATURATION              1031
#define IDC_STR_BLC_GRID                1031
#define IDC_EDIT_SATURATION             1032
#define IDC_COMBO_MIRROR_MODE2          1032
#define IDC_COMBO_BLC_GRID              1032
#define IDC_SLD_SHARPNESS               1033
#define IDC_STR_SHUT_LVL                1033
#define IDC_STR_EDGEGAIN_LVL            1033
#define IDC_EDIT_SHARPNESS              1034
#define IDC_SLD_SHUT_LVL                1034
#define IDC_SLD_EDGEGAIN_LVL            1034
#define IDC_SLD_WHTCOM                  1035
#define IDC_EDIT_SHUT_LVL               1035
#define IDC_EDIT_EDGEGAIN_LVL           1035
#define IDC_EDIT_WHTCOM                 1036
#define IDC_EDIT_BLCWLvl                1036
#define IDC_SLD_BCKLGTCOMP              1037
#define IDC_SLD_WHTCOM_RED              1037
#define IDC_SLD_AE_CTRLSPEED            1037
#define IDC_EDIT_BCKLGTCOMP             1038
#define IDC_EDIT_WHTCOM2_RED            1038
#define IDC_EDIT_WHTCOM_RED             1038
#define IDC_EDIT_AE_CTRLSPEED           1038
#define IDC_STR_BRIGHTNESS              1039
#define IDC_STR_AE_MAX_LVL              1039
#define IDC_STR_CONTRAST                1040
#define IDC_SLD_AE_MAX_LVL              1040
#define IDC_STR_HUE                     1041
#define IDC_EDIT_AE_MAX_LVL             1041
#define IDC_STR_SATURATION              1042
#define IDC_STR_SHARPNESS               1043
#define IDC_STR_WHTCOM                  1044
#define IDC_STR_WHTBLCMODE              1045
#define IDC_STR_3D_NOISE_REDU_VAL       1046
#define IDC_STR_2D_NOISE_REDU_VAL       1046
#define IDC_EDIT_3D_NOISE_REDU_VAL      1047
#define IDC_EDIT_2D_NOISE_REDU_VAL      1047
#define IDC_STR_BRAND_NAME              1048
#define IDC_STR_2D_NR_GAINSTR_VAL       1048
#define IDC_EDIT_2D_NR_GAINSTR_VAL      1049
#define IDC_STATIC_WH_COMP_RED          1050
#define IDC_STR_2D_NR_GAINEND_VAL       1050
#define IDC_EDIT_DEV_MAIN_ADDR          1051
#define IDC_EDIT_ADDR1                  1051
#define IDC_STATIC_WH_COMP_BLUE         1051
#define IDC_EDIT_2D_NR_GAINEND_VAL      1051
#define IDC_EDIT_DEV_MAIN_ADDR2         1052
#define IDC_EDIT_DEV_SUB_ADDR           1052
#define IDC_EDIT_ADDR2                  1052
#define IDC_STATIC_WH_COMP_RED2         1052
#define IDC_STR_DEV_SUB_ADDR            1053
#define IDC_EDIT_ADDR_BYTE              1053
#define IDC_HIGHTLOW_COLSUP_GAIN        1053
#define IDC_STR_REG_ADDR                1054
#define IDC_EDIT_DATA_BYTE              1054
#define IDC_EDIT_HIGHTLOW_COLSUP_GAIN   1054
#define IDC_EDIT_REG_ADDR               1055
#define IDC_EDIT_ADDR3                  1055
#define IDC_EDGE_COLSUP_GAIN            1055
#define IDC_STR_DATA                    1056
#define IDC_EDIT_EDGE_COLSUP_GAIN       1056
#define IDC_EDIT_DATA                   1057
#define IDC_EDIT_DATA1                  1057
#define IDC_STATIC_WH_COMP_BLUE2        1057
#define IDC_BTN_WRITE                   1058
#define IDC_BTN_READ                    1059
#define IDC_STR_DIG_ZOOM_POS            1060
#define IDC_EDIT_ADDR4                  1060
#define IDC_EDIT_DIG_ZOOM_POS           1061
#define IDC_EDIT_ADDR5                  1061
#define IDC_STR_OPT_ZOOM                1062
#define IDC_EDIT_ADDR6                  1062
#define IDC_STR_DIG_FOCUS_POS           1062
#define IDC_STR_OPT_ZOOM_MIN            1063
#define IDC_EDIT_DATA2                  1063
#define IDC_STR_DIG_ZOOMTRC_POS         1063
#define IDC_STR_DIG_FOCUS_POS2          1063
#define IDC_EDIT_OPT_ZOOM_MIN           1064
#define IDC_STR_DIG_FOCUSONE_POS        1064
#define IDC_STR_OPT_ZOOM_MAX            1065
#define IDC_EDIT_OPT_ZOOM_MAX           1066
#define IDC_RADIO4                      1066
#define IDC_STR_MANUAL_IRIS             1067
#define IDC_STR_OPT_ZOOM_TEST           1067
#define IDC_EDIT_MANUAL_IRIS            1068
#define IDC_STR_OPT_FOCUS_MANU          1068
#define IDC_STR_MANUAL_IRIS2            1069
#define IDC_EDIT_DIR                    1069
#define IDC_EDIT_AUTO_IRIS              1070
#define IDC_BTN_DIR                     1070
#define IDC_BTN_SNAPSHOT                1071
#define IDC_STR_CAM_MODE                1072
#define IDC_BTN_RESET                   1073
#define IDC_STR_CUR                     1074
#define IDC_BTN_SAVE                    1075
#define IDC_EDIT_USERNAME               1075
#define IDC_EDIT_PASS                   1076
#define IDC_STR_PASS                    1077
#define IDC_STR_STATUS                  1078
#define IDC_STR__AE_PRIORITY            1079
#define IDC_STR_STATUA_CAM_REC          1080
#define IDC_CHECK_AUTO_EXP              1081
#define IDC_CHECK_AUTO_EXP2             1082
#define IDC_CHECK_AUTO_IRIS             1082
#define IDC_STR_BLC_WGHT_FACT           1082
#define IDC_STR_Hpos                    1083
#define IDC_STR_VPos                    1084
#define IDC_SLD_VPos                    1085
#define IDC_STR_HSize                   1086
#define IDC_SLD_VSize                   1087
#define IDC_BTN_ZOOM_IN                 1087
#define IDC_STR_VSize                   1088
#define IDC_BTN_ZOOM_OUT                1088
#define IDC_BTN_ZOOM_IN2                1089
#define IDC_BTN_ZOOM_STOP               1089
#define IDC_BTN_FOCUS_START             1089
#define IDC_SLD_BLCWLvl                 1089
#define IDC_BTN_FOCUS_NEAR              1090
#define IDC_BTN_FOCUS_FAR               1091
#define IDC_COMBO_FOCUS_MODE            1092
#define IDC_COMBO_FOCUS_ZOOMTRC         1093
#define IDC_FINE_SHUTTER_ENABLE         1093
#define IDC_COMBO_ROI_MODE              1094
#define IDC_2DNR_ENABL                  1094
#define IDC_COMBO_STIL_RES              1095
#define IDC_COMBO_STIL_VIDTYPE          1096
#define IDC_WBL_P2W_ENABL               1096
#define IDC_COLOR_SUPPRESSION_ENABL     1097
#define IDC_COLOR_SUPPRE_GAIN_VAL       1098
#define IDC_COLSUP_AGC_START            1099
#define IDC_COLSUP_AGC_END              1100
#define IDC_SLD_COLSUPP_GAIN_VAL        1101
#define IDC_EDIT_COLSUPP_GAIN_VAL       1102
#define IDC_SLD_COLSUPP_GAINSTR_VAL     1103
#define IDC_EDIT_COLSUPP_GAINSTR_VAL    1104
#define IDC_SLD_COLSUPP_GAINEND_VAL     1105
#define IDC_EDIT_COLSUPP_GAINEND_VAL    1106
#define IDC_STR_3D_NOISE_REDU_MODE      1146
#define IDC_STR_GAMMA_MODE              1146
#define ID_FILE_CHOOSEDEVICE            40001
#define ID_SETTING_MIRROR               40002
#define ID_SETTING                      40003
#define ID_SETTING_EXTENDED             40004
#define ID_SETTING_STANDARD             40005
#define MENU_CAM_CONTROL                40006
#define MENU_DAY                        40007
#define MENU_DAY_NIGHT_SETTING          40008
#define ID_SETTING_VIDEOQUALITYSETTINGS 40009
#define ID_SETTING_3DNOISEREDUCTION     40010
#define MENU_ABOUT                      40011
#define ID_SETTINGS_I2CCONTROLS         40012
#define MENU_I2C_CONTROL                40013
#define ID_SETTINGS_ZOOMCONTROLS        40014
#define MENU_ZOOM                       40015
#define MENU_ZOOM_CONTROL               40016
#define ID_SETTINGS_IRISCONTROLS        40017
#define MENU_IRIS_CONTROL               40018
#define ID_SETTINGS_IMAGECAPTURE        40019
#define MENU_IMAGE_CAPTURE              40020
#define MENU_CAM_PARAM_RECOVERY         40021
#define ID_SETTINGS_VIDEO               40022
#define ID_FORMAT_VIDEORESOLUTION       40023
#define ID_FORMAT_REGIONOFINTREST       40024
#define ID_SNAPSHOT_GETIMAGE            40025
#define ID_SNAPSHOT_SETIMAGERESOLUTION  40026
#define ID_SNAPSHOT_SETSAVINGDIRECTORY  40027
#define ID_VIDEOLOGYOPTION_5MPB         40028
#define ID_IMAGECAPTURE                 40029
#define ID_OPTION_PLAYBACKSTYLE         40030
#define ID_PLAYBACKSTYLE_FULLIMAGE      40031
#define ID_PLAYBACKSTYLE_ORIGINALPIXELS 40032
#define ID_5MPCAMERASETTINGS_SHU        40033
#define ID_5MPCAMERASETTINGS_EDGEENHANCEMENT 40034
#define ID_5MPCAMERASETTINGS_GAMMAAND2DNR 40035
#define ID_5MPCAMERASETTINGS_SHUT       40036
#define ID_VIDEOLOGYOPTION_CAMERAMANAGEMENT 40037
#define ID_CAMERA_SAVEPARAMETERS        40038
#define ID_CAMERA_RESETSETTINGS         40039
#define VIS_CAMERA_MENU                 40040
#define ID_SETTING_VIDEOQUALITYSETTINGS_MISU 40041
#define ID_CAMERASETTINGS_SHUT_20_12MC  40042
#define ID_FOCUS_ZOOM_SETTINGS_20_12MC  40043
#define ID_CAMERA_TERMINAL_SETTINGS_20_12MC 40044
#define ID_DAYNIGHTSETTINGS_20_12MC     40045
#define ID_3DNR_SETTINGS_20_12MC        40046
#define ID_SETTING_VIDEOQUALITYSETTINGS_20_12MC 40047
#define ID_5MPCOLCAMERASETTINGS_WBLCOLSUPPRESSION 40048
#define ID_5MPCOLCAMERAMANAGEMENT_PIXELCORRECTION 40049
#define IDC_STR_DAY_NIGHT_MODE          -1
#define IDC_STR_BCKLGTCOMP              -1
#define IDC_STR_DEV_MAIN_ADDR           -1
#define IDC_STR_DIG_ZOOM                -1
#define IDC_STR_LENSE                   -1
#define IDC_STR_DIR                     -1
#define IDC_STR_DEF                     -1
#define IDC_STR_USERNAME                -1
#define IDC_STR_AUTO                    -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40050
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
